-- ==============================================================================
-- Quantitative Portfolio Backtesting Platform - Database Schema
-- ==============================================================================
-- 
-- Why DuckDB?
-- DuckDB was chosen for this platform because it is an in-process SQL OLAP 
-- database management system. It provides excellent performance for analytical 
-- queries (like those used in backtesting and financial data analysis) due to 
-- its columnar storage and vectorized query execution engine. It's incredibly 
-- easy to set up (no separate server process required) and natively supports 
-- analytical window functions and complex aggregations common in quantitative finance.
-- 
-- Schema Design Rationale:
-- This schema is designed in a normalized fashion to ensure data integrity and 
-- ease of querying. 
-- - 'assets' acts as the core dimension table for financial instruments.
-- - 'price_data' stores the time-series price history (fact table).
-- - 'strategies' stores metadata about the different backtested models.
-- - 'portfolio_weights' records the target allocations generated by strategies over time.
-- - 'backtest_results' tracks the daily performance (equity curve) of each strategy.
-- - 'risk_metrics' stores computed summary statistics (Sharpe, Drawdown, etc.) for strategies.
-- 
-- Migration Note (DuckDB to PostgreSQL):
-- DuckDB uses a PostgreSQL-compatible SQL dialect. The syntax used in this schema 
-- (data types, constraints, index creation) is identical to PostgreSQL. To migrate 
-- to a PostgreSQL instance, you simply need to change the connection string in your 
-- application code; no changes to these SQL definitions are necessary.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- Table: assets
-- Description: Stores metadata about the financial instruments being traded.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS assets (
    asset_id INTEGER PRIMARY KEY,
    ticker VARCHAR UNIQUE NOT NULL,    -- Ticker symbol (e.g., 'AAPL')
    name VARCHAR,                      -- Full company or fund name
    sector VARCHAR,                    -- Economic sector (e.g., 'Technology')
    exchange VARCHAR                   -- Exchange listed on (e.g., 'NASDAQ')
);

-- ------------------------------------------------------------------------------
-- Table: price_data
-- Description: Stores daily historical price data for the assets.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS price_data (
    price_id INTEGER PRIMARY KEY,
    asset_id INTEGER REFERENCES assets(asset_id), -- Foreign key to assets table
    date DATE NOT NULL,                           -- Trading date
    adj_close DOUBLE NOT NULL,                    -- Dividend/split-adjusted close price
    UNIQUE(asset_id, date)                        -- Ensure one price per asset per day
);

CREATE INDEX IF NOT EXISTS idx_price_date ON price_data(date);
CREATE INDEX IF NOT EXISTS idx_price_asset ON price_data(asset_id);

-- ------------------------------------------------------------------------------
-- Table: strategies
-- Description: Stores metadata about the quantitative trading strategies.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS strategies (
    strategy_id INTEGER PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL,      -- Short name of the strategy
    description VARCHAR                -- Detailed explanation of strategy logic
);

-- ------------------------------------------------------------------------------
-- Table: portfolio_weights
-- Description: Stores the asset allocation weights generated by a strategy on a given date.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS portfolio_weights (
    weight_id INTEGER PRIMARY KEY,
    strategy_id INTEGER REFERENCES strategies(strategy_id), -- Foreign key to strategies
    asset_id INTEGER REFERENCES assets(asset_id),           -- Foreign key to assets
    date DATE NOT NULL,                                     -- Rebalance or signal date
    weight DOUBLE NOT NULL                                  -- Allocation weight (e.g., 0.05 for 5%)
);

CREATE INDEX IF NOT EXISTS idx_weights_date ON portfolio_weights(date);
CREATE INDEX IF NOT EXISTS idx_weights_strategy ON portfolio_weights(strategy_id);

-- ------------------------------------------------------------------------------
-- Table: backtest_results
-- Description: Stores the daily simulated portfolio value and returns of a strategy.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS backtest_results (
    result_id INTEGER PRIMARY KEY,
    strategy_id INTEGER REFERENCES strategies(strategy_id), -- Foreign key to strategies
    date DATE NOT NULL,                                     -- Backtest date
    portfolio_value DOUBLE NOT NULL,                        -- Total equity/value on date
    daily_return DOUBLE,                                    -- Percentage return from previous day
    UNIQUE(strategy_id, date)                               -- Ensure one result per strategy per day
);

CREATE INDEX IF NOT EXISTS idx_backtest_date ON backtest_results(date);
CREATE INDEX IF NOT EXISTS idx_backtest_strategy ON backtest_results(strategy_id);

-- ------------------------------------------------------------------------------
-- Table: risk_metrics
-- Description: Stores calculated summary risk and performance metrics for strategies.
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS risk_metrics (
    metric_id INTEGER PRIMARY KEY,
    strategy_id INTEGER REFERENCES strategies(strategy_id), -- Foreign key to strategies
    metric_name VARCHAR NOT NULL,                           -- e.g., 'Annualized Return', 'Sharpe Ratio'
    metric_value DOUBLE,                                    -- Computed value of the metric
    computed_date DATE,                                     -- Date the metric was computed
    UNIQUE(strategy_id, metric_name)                        -- One unique metric type per strategy
);
